import { normalizeString } from './helpers';
import { getProductCategory } from './categories';

// Specific product icons mapping
export const PRODUCT_ICONS: { [key: string]: string } = {
  // Laticínios
  'leite': '🥛',
  'queijo': '🧀',
  'mussarela': '🧀',
  'mozzarella': '🧀',
  'parmesão': '🧀',
  'parmesan': '🧀',
  'ricota': '🧀',
  'cream cheese': '🧀',
  'requeijão': '🧀',
  'iogurte': '🥛',
  'manteiga': '🧈',
  'creme de leite': '🥛',
  'nata': '🥛',
  
  // Carnes
  'carne': '🥩',
  'bife': '🥩',
  'picanha': '🥩',
  'alcatra': '🥩',
  'patinho': '🥩',
  'acém': '🥩',
  'costela': '🥩',
  'coxão': '🥩',
  'maminha': '🥩',
  'filé mignon': '🥩',
  'cupim': '🥩',
  'bacon': '🥓',
  'linguiça': '🌭',
  'salsicha': '🌭',
  'presunto': '🥓',
  'mortadela': '🥓',
  'tender': '🍖',
  
  // Aves
  'frango': '🍗',
  'peito de frango': '🍗',
  'coxa': '🍗',
  'sobrecoxa': '🍗',
  'peru': '🦃',
  
  // Peixes e Frutos do Mar
  'peixe': '🐟',
  'salmão': '🍣',
  'tilápia': '🐟',
  'bacalhau': '🐟',
  'atum fresco': '🐟',
  'sardinha fresca': '🐟',
  'merluza': '🐟',
  'pescada': '🐟',
  'robalo': '🐟',
  'anchova': '🐟',
  'camarão': '🦐',
  'lula': '🦑',
  'polvo': '🐙',
  'caranguejo': '🦀',
  'lagosta': '🦞',
  
  // Frutas
  'maçã': '🍎',
  'maca': '🍎',
  'banana': '🍌',
  'laranja': '🍊',
  'tangerina': '🍊',
  'mexerica': '🍊',
  'uva': '🍇',
  'abacaxi': '🍍',
  'manga': '🥭',
  'mamão': '🥭',
  'melão': '🍈',
  'melancia': '🍉',
  'morango': '🍓',
  'limão': '🍋',
  'abacate': '🥑',
  'pêra': '🍐',
  'pera': '🍐',
  'pêssego': '🍑',
  'pessego': '🍑',
  'kiwi': '🥝',
  'goiaba': '🍈',
  'maracujá': '🥝',
  'maracuja': '🥝',
  'acerola': '🍒',
  'cereja': '🍒',
  'ameixa': '🍑',
  'coco': '🥥',
  'fruta': '🍎',
  
  // Vegetais e Legumes
  'cenoura': '🥕',
  'batata': '🥔',
  'tomate': '🍅',
  'alface': '🥬',
  'cebola': '🧅',
  'alho': '🧄',
  'brócolis': '🥦',
  'brocolis': '🥦',
  'couve': '🥬',
  'espinafre': '🥬',
  'repolho': '🥬',
  'pepino': '🥒',
  'abobrinha': '🥒',
  'berinjela': '🍆',
  'pimentão': '🫑',
  'pimentao': '🫑',
  'pimenta': '🌶️',
  'beterraba': '🥬',
  'vagem': '🥬',
  'quiabo': '🥬',
  'jiló': '🥬',
  'chuchu': '🥬',
  'abóbora': '🎃',
  'abobora': '🎃',
  'mandioca': '🥔',
  'inhame': '🥔',
  'verdura': '🥬',
  'legume': '🥬',
  'salada': '🥗',
  'rúcula': '🥬',
  'rucula': '🥬',
  'agrião': '🥬',
  'agriao': '🥬',
  'acelga': '🥬',
  'milho verde': '🌽',
  'milho': '🌽',
  
  // Padaria
  'pão': '🍞',
  'pao': '🍞',
  'pão francês': '🥖',
  'pão de forma': '🍞',
  'bisnaguinha': '🥖',
  'baguete': '🥖',
  'bolo': '🎂',
  'torrada': '🍞',
  'croissant': '🥐',
  'rosca': '🥯',
  'sonho': '🍩',
  'pão de queijo': '🧀',
  'brioche': '🥐',
  'massa folhada': '🥐',
  
  // Bebidas
  'água': '💧',
  'agua': '💧',
  'suco': '🧃',
  'refrigerante': '🥤',
  'coca': '🥤',
  'coca-cola': '🥤',
  'guaraná': '🥤',
  'guarana': '🥤',
  'fanta': '🥤',
  'sprite': '🥤',
  'cerveja': '🍺',
  'vinho': '🍷',
  'vinho tinto': '🍷',
  'vinho branco': '🥂',
  'champagne': '🍾',
  'espumante': '🍾',
  'whisky': '🥃',
  'vodka': '🍸',
  'cachaça': '🥃',
  'cachaca': '🥃',
  'tônica': '🥤',
  'tonica': '🥤',
  'energético': '🥤',
  'energetico': '🥤',
  'isotônico': '🥤',
  'isotonico': '🥤',
  'chá gelado': '🧋',
  
  // Limpeza
  'detergente': '🧴',
  'sabão': '🧼',
  'sabao': '🧼',
  'água sanitária': '🧴',
  'agua sanitaria': '🧴',
  'desinfetante': '🧴',
  'amaciante': '🧴',
  'lava roupas': '🧺',
  'alvejante': '🧴',
  'limpa vidro': '🪟',
  'esponja': '🧽',
  'pano': '🧹',
  'vassoura': '🧹',
  'rodo': '🧹',
  'lustra móveis': '🧴',
  'multiuso': '🧴',
  'cloro': '🧴',
  'saco de lixo': '🗑️',
  'limpeza': '🧹',
  
  // Higiene Pessoal
  'shampoo': '🧴',
  'condicionador': '🧴',
  'sabonete': '🧼',
  'pasta de dente': '🪥',
  'creme dental': '🪥',
  'escova de dente': '🪥',
  'papel higiênico': '🧻',
  'papel higienico': '🧻',
  'desodorante': '🧴',
  'fio dental': '🪥',
  'absorvente': '🩹',
  'fralda': '👶',
  'algodão': '☁️',
  'algodao': '☁️',
  'cotonete': '🩹',
  'hidratante': '🧴',
  'protetor solar': '🧴',
  'barbeador': '🪒',
  'gilete': '🪒',
  'veja': '🧴',
  
  // Cereais e Grãos
  'arroz': '🍚',
  'feijão': '🫘',
  'feijao': '🫘',
  'aveia': '🌾',
  'granola': '🥣',
  'cereal': '🥣',
  'sucrilhos': '🥣',
  'corn flakes': '🥣',
  'trigo': '🌾',
  'quinoa': '🌾',
  'lentilha': '🫘',
  'grão de bico': '🫘',
  'grao de bico': '🫘',
  'soja': '🫘',
  'ervilha seca': '🫘',
  'farinha': '🌾',
  'fubá': '🌾',
  'fuba': '🌾',
  'polenta': '🌾',
  'canjica': '🌾',
  
  // Biscoitos e Snacks
  'bolacha': '🍪',
  'biscoito': '🍪',
  'cookie': '🍪',
  'wafer': '🍪',
  'cream cracker': '🍪',
  'rosquinha': '🍩',
  'salgadinho': '🍿',
  'chips': '🍟',
  'doritos': '🍿',
  'ruffles': '🍟',
  'torcida': '🍿',
  'cheetos': '🍿',
  'snack': '🍿',
  'chocolate': '🍫',
  'barra de cereal': '🥣',
  'amendoim': '🥜',
  'castanha': '🥜',
  'pipoca': '🍿',
  
  // Enlatados e Conservas
  'atum': '🥫',
  'sardinha': '🥫',
  'ervilha': '🫛',
  'molho de tomate': '🍅',
  'extrato': '🥫',
  'azeitona': '🫒',
  'palmito': '🥫',
  'seleta': '🥫',
  'champignon': '🍄',
  'cogumelo': '🍄',
  'catchup': '🍅',
  'ketchup': '🍅',
  'mostarda': '🟡',
  'maionese': '🥫',
  'conserva': '🥫',
  'enlatado': '🥫',
  
  // Congelados
  'pizza': '🍕',
  'sorvete': '🍦',
  'hambúrguer': '🍔',
  'hamburguer': '🍔',
  'lasanha': '🍝',
  'nuggets': '🍗',
  'empanado': '🍗',
  'batata frita': '🍟',
  'congelado': '❄️',
  'picolé': '🍦',
  'picole': '🍦',
  'açaí': '🍇',
  'acai': '🍇',
  'polpa': '🍓',
  'massa pronta': '🍝',
  
  // Café e Chás
  'café': '☕',
  'cafe': '☕',
  'chá': '🍵',
  'cha': '🍵',
  'cappuccino': '☕',
  'achocolatado': '🍫',
  'nescau': '🍫',
  'toddy': '🍫',
  'filtro de café': '☕',
  'cápsula': '☕',
  'capsula': '☕',
  
  // Ovos
  'ovo': '🥚',
  'ovos': '🥚',
  
  // Temperos e Condimentos
  'açúcar': '🍬',
  'acucar': '🍬',
  'sal': '🧂',
  'óleo': '🫒',
  'oleo': '🫒',
  'azeite': '🫒',
  'vinagre': '🍶',
  'tempero': '🧂',
  'orégano': '🌿',
  'oregano': '🌿',
  'manjericão': '🌿',
  'manjericao': '🌿',
  'canela': '🌰',
  'cravo': '🌰',
  'noz moscada': '🌰',
  'colorau': '🌶️',
  'cominho': '🌿',
  'curry': '🌿',
  'páprica': '🌶️',
  'paprica': '🌶️',
  'louro': '🌿',
  'alecrim': '🌿',
  'salsinha': '🌿',
  'cebolinha': '🌿',
  'coentro': '🌿',
  'sazon': '🧂',
  'knorr': '🧂',
  'caldo': '🧂',
  'condimento': '🧂',
  
  // Massas
  'macarrão': '🍝',
  'macarrao': '🍝',
  'espaguete': '🍝',
  'spaghetti': '🍝',
  'penne': '🍝',
  'fusilli': '🍝',
  'talharim': '🍝',
  'lasanha seca': '🍝',
  'massa': '🍝',
  'nhoque': '🍝',
  'capeletti': '🍝',
  'ravioli': '🍝',
  
  // Doces e Pastas
  'mel': '🍯',
  'geleia': '🍓',
  'doce de leite': '🥛',
  'nutella': '🍫',
  'amendocreme': '🥜',
  'leite condensado': '🥛',
  'creme de avelã': '🌰',
  
  // Pet Shop
  'ração': '🐕',
  'racao': '🐕',
  'petisco pet': '🐾',
  'sachê': '🐱',
  'sache': '🐱',
  'areia de gato': '🐱',
  'comedouro': '🐾',
  'antipulgas': '🐕',
};

// Get specific product icon
export function getSpecificProductIcon(productName: string): string {
  const nameNormalized = normalizeString(productName);
  
  // Check for exact matches first (longer keywords first for better matching)
  const sortedKeywords = Object.keys(PRODUCT_ICONS).sort((a, b) => b.length - a.length);
  
  for (const keyword of sortedKeywords) {
    if (nameNormalized.includes(normalizeString(keyword))) {
      return PRODUCT_ICONS[keyword];
    }
  }
  
  // If no specific icon found, return from category or default
  return getProductCategory(productName).icon;
}

